[package]
name = "cacache"
version = "9.0.1-alpha.0"
authors = ["Kat March√°n <kzm@zkat.tech>"]
edition = "2018"
description = "Content-addressable, key-value, high-performance, on-disk cache."
license = "Apache-2.0"
repository = "https://github.com/zkat/cacache-rs"
homepage = "https://github.com/zkat/cacache-rs"
readme = "README.md"
categories = [
    "caching",
    "filesystem"
]

[dependencies]
ssri = "7.0.0"
hex = "0.4.3"
tempfile = "3.2.0"
sha-1 = "0.9.8"
sha2 = "0.9.8"
digest = "0.9.0"
serde_json = "1.0.68"
serde = "1.0.130"
serde_derive = "1.0.130"
walkdir = "2.3.2"
either = "1.6.1"
async-std = { version = "1.10.0", features = ["unstable"] }
thiserror = "1.0.29"
futures = "0.3.17"
memmap = "0.7.0"

[dev-dependencies]
async-attributes = "1.1.2"
criterion = "0.3.5"

[[bench]]
name = "benchmarks"
harness = false
