[package]
name = "cacache"
version = "1.0.1"
authors = ["Kat March√°n <kzm@zkat.tech>"]
edition = "2018"
description = "Content-addressable, key-value, high-performance, on-disk cache."
license-file = "LICENSE.md"
repository = "https://github.com/zkat/cacache-rs"
homepage = "https://github.com/zkat/cacache-rs"
readme = "README.md"
categories = [
    "caching",
    "filesystem"
]

[badges]
travis-ci = { repository = "zkat/cacache-rs", branch = "latest" }
maintenance = { status = "actively-developed" }

[dependencies]
ssri = "4.0.0"
hex = "0.3.2"
tempfile = "3.0.8"
sha-1 = "0.8.1"
sha2 = "0.8.0"
digest = "0.8.0"
serde_json = "1.0.39"
serde = "1.0.92"
serde_derive = "1.0.92"
failure = "0.1.5"
walkdir = "2.2.7"
either = "1.5.2"
mkdirp = "1.0.0"
futures-preview = "0.3.0-alpha.18"
async-std = { version = "0.99.9", features = ["unstable"]}

[target.'cfg(unix)'.dependencies]
chownr = "2.0.0"
nix = "0.14.0"

[dev-dependencies]
criterion = "0.2.11"

[[bench]]
name = "benchmarks"
harness = false
