[package]
name = "cacache"
version = "0.1.0"
authors = ["Kat March√°n <kzm@zkat.tech>"]
edition = "2018"

[dependencies]
ssri = "1.1.0"
hex = "0.3.2"
atomicwrites = "0.2.2"
tempfile = "3.0.8"
sha-1 = "0.8.1"
sha2 = "0.8.0"
digest = "0.8.0"
serde_json = "1.0.39"
serde = "1.0.91"
serde_derive = "1.0.91"
